### ISSUE TITLE
setup should behave as a config file

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright-test#112]
The config pattern like eslintrc.js and jest.config.json makes sense for setup.ts.

**Comment by mxschmitt** [comment]
(just thoughts)

Pytest has the concept of a `conftest.py` file which you can drop in folders. Each folder would overwrite the parent `conftest.py`'s content if you redefine fixtures e.g.

These conftest files can be extracted into own NPM packages to outsource specific features. (we can do this already)

Also they support adding new CLI parameters which result in parameters in the end which tests and fixtures can use. (we can do this already).

In pytest for configuring something fixtures will be mostly redefined.

What kind of settings would you like to put into such a config?

**Comment by pavelfeldman** [comment]
Config in this context is a substitute for the cli args. That and the before, after and parameters.

We can't do the pytest conftest story due to typing - tests need to explicitly require fixture files in order to be typed.

**Comment by mrmckeb** [comment]
If you'd be open to a PR, I'd be happy to pick up a config file task.

We've just started testing `playwright-test` and can see that there would be immediate benefit to some kind of `playwright-test.config.ts` file, or similar.

Perhaps also `setup` and `teardown` files, or similar?

**Comment by arjunattam** [comment]
Thanks, @mrmckeb. Can you tell us more on what you think the config, setup, teardown should have? Thanks for helping us shape the test runner!

**Comment by mrmckeb** [comment]
Hi @arjunattam, we think (from our experience so far) that at a minimum it would be good to set the CLI flags in a config instead.

For us, global setup and teardown might be something like setting up a new tenant/account, or seeding users and other account data programmatically - and then cleaning those up at the end of a test run.

It might also be valuable to have the ability to pass something from setup to tests (via test function parameter, or `global` context for example). This is something missing in some other test frameworks.

We understand there are many workarounds in the meantime, and that this isn't critical - but some of this would make the setup experience nicer.

**Comment by mxschmitt** [comment]
Closing since the [new test-runner](https://playwright.dev/docs/test-intro) includes now a global setup and teardown file. See here: https://playwright.dev/docs/test-advanced#global-setup-and-teardown
