### ISSUE TITLE
screenshot-on-failure option not exists

### ISSUE THREAD

**Issue by dareksob** [microsoft/playwright-test#146]
# Take screenshots on failure
npx test-runner --screenshot-on-failure

This example not work, option not exists.

````
error: unknown option '--screenshot-on-failure'
error Command failed with exit code 1.
````

node: 
    "playwright-cli": "next",
    "@playwright/test": "^0.9.10",
    "@playwright/test-runner": "^0.9.22"

node -v
v12.18.4

**Comment by arjun27** [comment]
Thanks for reporting. The syntax for parameters has changed. You can use -h to see it for the version installed. I’ll update the docs today.
