### ISSUE TITLE
describe not exists or not a function

### ISSUE THREAD

**Issue by dareksob** [microsoft/playwright-test#147]
```````
const { it, describe, beforeAll, beforeEach, afterAll, afterEach } = require('@playwright/test');

describe('feature foo', () => {
  it('is working correctly', async ({ page }) => {
    // Test function
    // ...
  })
});

```````

I get this error

TypeError: describe is not a function

    "playwright-cli": "next",
    "@playwright/test": "^0.9.10",
    "@playwright/test-runner": "^0.9.22"

**Comment by mxschmitt** [comment]
Hi, the change is pretty new and not yet released. #145

**Comment by dareksob** [comment]
the it function also not work. 
The export of the include file not correct.
I found the fixtures object which have the functions.

const {it} = require('@playwright/test').fixtures;

**Comment by turbobasti** [comment]
I have tried many things, but I can't get it work. The fixtures it doesn't have the page and context as argument. I have also tried different versions and link the current master as module but without success.

**Comment by arjunattam** [comment]
Thanks for trying it out, @dareksob and @turbobasti. This project is under active development and things are changing rapidly. Parts of the readme are outdated and are being updated. We are very close to sharing it more broadly. Stay tuned :)
