### ISSUE TITLE
Nice node debugging experience

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright-test#148]
- [x] node source maps in vscode
- [x] node breakpoints in vscode
- [ ] `--inspect`/`--inspect-brk`. This should probably force a single process mode, and do something fancy with timeouts
- [ ] Print each test line as it runs. We had `dit` in the old runner and it was very nice, but the UI needs some thought.

**Comment by arjun27** [comment]
Thanks for opening this!

> node breakpoints in vscode

While this works today, the default timeout of 10s needs to be changed when execution is paused on a breakpoint.
