### ISSUE TITLE
npx @playwright/test should do something

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright-test#149]
Right now it throws an error about something being missing.

```
Cannot find module '@playwright/test-runner/cli'
Require stack:
- /Users/joeleinbinder/pw-test-pg/node_modules/@playwright/test/cli.js
```

**Comment by mxschmitt** [comment]
Background: Test-runner is now an optional dependency. We should in mind change it back to a dependency.

**Comment by JoelEinbinder** [comment]
It could also just tell me to install @playwright/test-runner
