### ISSUE TITLE
Add docs for visual comparison expect API

### ISSUE THREAD

**Issue by JosefJezek** [microsoft/playwright-test#152]
Could you add support for visual testing?

see on this solutions
- https://codecept.io/visual/#using-resemble-helper
- https://theheadless.dev/posts/basics-taking-screenshots/#use-in-visual-regression-testing

**Comment by arjunattam** [comment]
Thanks @JosefJezek! We have added support for visual comparisons. I'll reframe this to track adding that to our docs.
