### ISSUE TITLE
Basic example tests seem to be broken

### ISSUE THREAD

**Issue by jordangarside** [microsoft/playwright-test#154]
I just updated from `0.9.6` to `0.9.16` and started getting this error when running any of my tests:

```
TypeError: Cannot read property 'it' of undefined

  3 | import { LoginPage } from '.'
  4 | 
> 5 | it(
    | ^
  6 |   'should render the login page without CORS errors',
  7 |   (test, params) => {

    at FolioImpl.it.args (/Users/jordan.garside/app/node_modules/folio/out/spec.js:32:28)
    at Object.<anonymous> (/Users/jordan.garside/app/test/index.test.ts:5:1)
```

L1: `import { it, expect } from '@playwright/test'`

It looks like `folio` was added as a dependency at some point.

**Comment by arjunattam** [comment]
Hey @jordangarside. We renamed microsoft/playwright-test-runner to [microsoft/folio](https://github.com/microsoft/folio), which is also now [published to NPM](https://www.npmjs.com/package/folio). Folio continues to be the foundation for this package, which is called @playwright/test.

We have been re-working the API for a preview release, which probably broke something here. The syntax for `it` seems correct to me but I suspect the command to run the test needs to be changed. I've updated the [getting started section](https://github.com/microsoft/playwright-test#get-started) for the latest bits.

**Comment by jordangarside** [comment]
Gotcha, will take a look thanks!

**Comment by jordangarside** [comment]
Yeah seems to be working correctly with `folio` instead of `@playwright/test-runner`. 👍

**Comment by andrewmclagan** [comment]
I'm confused sorry. Having the import from:

```javascript
const { it, expect } = require('@playwright/test');
```

Breaks with the error the op noted above.

**Comment by rdrwoodall-s5** [comment]
I am seeing the same behavior as @andrewmclagan above when following the latest documentation from the readme. @jordangarside can you clarify how you were able to get this working please?

**Comment by jordangarside** [comment]
Follow the instructions here:
https://github.com/microsoft/folio#with-fixtures

I just install `@playwright/test`, and then do this:
```
import { folio } from '@playwright/test'

const fixtures = folio.extend()

const { it, expect } = fixtures.build();
```
