### ISSUE TITLE
Take "screenshot on failure" if fixture fails

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright-test#165]
When fixtures involve browser interaction steps, these steps can fail. In such cases, debug artifacts like screenshots on failure are useful to debug the issue. These artifacts are not guaranteed to be available today.

To repro
- Update `loggedInState` fixture inside examples/login-once-per-worker to fail
- Run with `-p screenshotOnFailure`

**Comment by pavelfeldman** [comment]
Unfortunately, this is a folio limitation:

Screenshot on failure is implemented as a test fixture, this fixture is only set up after the worker fixtures it depends upon are set up. `loggedInState` is a worker fixture, so when it fails, test fixtures don't run, test does not run, nothings runs. `loggedInState` author is responsible for try/catching it all, handling timeouts an capturing the screenshots.
