### ISSUE TITLE
[Feature] Add support for video on failure

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright-test#170]
Currently, the `-p video` parameter records videos for all runs. It would be useful to have videos recorded only on failure.

**Comment by mxschmitt** [comment]
For that it would be cool if we can lead the user to this GitHub Action, so they have directly an overview how they can integrate it with the CI provider: https://github.com/actions/upload-artifact

**Comment by vincent-prz** [comment]
Very interested in this feature as well - it would considerably speed up my builds.

**Comment by mxschmitt** [comment]
This feature is now integrated and called `'retain-on-failure'`. See here: https://playwright.dev/docs/test-configuration#configure-browser-context-videos-and-screenshots
