### ISSUE TITLE
Config for browser launch and context options

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright-test#176]
Users that want to modify options for browser launch/new context need to use fixtures today. We could explore simplifying this cognitive overhead with a config file and leave fixtures for more sophisticated scenarios.

Example scenarios
* Toggle `ignoreHTTPSErrors` on context
* Set device emulation for context
* Modify executablePath because tests only run on Edge Dev
* Using custom args for browsers
* Specify which browsers to run their tests on

**Comment by mxschmitt** [comment]
There is a config file now which can be used to create projects for setting custom launch and context options: https://playwright.dev/docs/test-configuration
