### ISSUE TITLE
Global setup phase

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright-test#177]
To avoid repetitive execution of authentication steps, some of our users rely on a global setup that 1/ logs in via the UI, 2/ extracts login state (cookies/storage), and 3/ load state in new contexts with beforeEach. To enable this scenario, the Playwright test runner could support a global setup phase.

**Comment by andrewmclagan** [comment]
I came here looking for just this. Elaborating on our use-case:

* Global async run once setup phase: Used for running initial app migrations / seeds

**Comment by jsjoeio** [comment]
Are there any updates on this? Looking to migrate from `playwright-test` and we would like this.

Our global setup currently looks like [this](https://github.com/cdr/code-server/blob/main/test/utils/globalSetup.ts).

**Comment by dgozman** [comment]
> Are there any updates on this? Looking to migrate from `playwright-test` and we would like this.
> 
> Our global setup currently looks like [this](https://github.com/cdr/code-server/blob/main/test/utils/globalSetup.ts).

It is currently only documented in upstream folio: https://github.com/microsoft/folio#global-setup-and-teardown. We are working on the better documentation here.

**Comment by mxschmitt** [comment]
We have a global setup now integration, see here: https://playwright.dev/docs/test-advanced#global-setup-and-teardown
