### ISSUE TITLE
Allow running same tests against multiple browsers parallelly. Is it possible with playwright-test?

### ISSUE THREAD

**Issue by tanvee38** [microsoft/playwright-test#185]
Thanks for the amazing test framework! I have some end-to-end tests using playwright and I am using jest as the test runner. I want to run the same tests against Chrome, Firefox and Safari parallelly where the tests within a test file should run sequentially. I know that jest-playwright does not have this flexibility to run same tests across multiple browsers parallelly. Kindly let me know if I can do it with playwright-test? Or if no, is there any plan to implement this feature? Testing an application for cross-browser compatibility is very valuable, and running them in parallel enormously saves CI time. playwright-test could make it much simpler. Kindly let me know your suggestions.Thanks in advance!

**Comment by pavelfeldman** [comment]
Yes, that's what happens in playwright-test by default.

**Comment by tanvee38** [comment]
Just tested it myself. Worked great! Thanks @pavelfeldman!
