### ISSUE TITLE
how to pass target url

### ISSUE THREAD

**Issue by Djelloul007** [microsoft/playwright-test#190]
Hello 

Thanks for your efort .

how to pass target url ?

Best regard
Dj

**Comment by mxschmitt** [comment]
You can do that e.g. with environment variables.

`TARGET_URL=https://staging.foo.bar folio tests`

and in the code you can access it with `console.log(process.env.TARGET_ENV)`.

Does this fit for your needs?

**Comment by Djelloul007** [comment]
See  Parameterize your tests
https://github.com/microsoft/playwright-test/tree/mxschmitt-docs/rename-test-runner-npx

**Comment by Djelloul007** [comment]
See  Parameterize your tests
https://github.com/microsoft/playwright-test/tree/mxschmitt-docs/rename-test-runner-npx
