### ISSUE TITLE
how to pass userName & Password 

### ISSUE THREAD

**Issue by Djelloul007** [microsoft/playwright-test#191]
Hello

Thanks for your efort .

how to pass userName & Password ?

Best regard
Dj

**Comment by mxschmitt** [comment]
See #190. Should also fit for that use case.

**Comment by Djelloul007** [comment]
Thanks @mxschmitt 
 
"scripts": {
    "test": "set TARGET_URL=http://todomvc.com/examples/react/#/ && npx folio --param screenshotOnFailure --param video --retries 1 --param headful --param browserName=chromium"
  }

**Comment by mxschmitt** [comment]
> Thanks @mxschmitt
> 
> "scripts": {
> "test": "set TARGET_URL=http://todomvc.com/examples/react/#/ && npx folio --param screenshotOnFailure --param video --retries 1 --param headful --param browserName=chromium"
> }

If you want to have it also compatible for Linux etc, then you can use cross-env: http://npmjs.com/package/cross-env

**Comment by Djelloul007** [comment]
Thanks Max for your Support.
By the way do you know how to generate a html report  ?

Thanks 
Dj from Karlsruhe
