### ISSUE TITLE
npx folio returns Timeout of 30000ms exceeded

### ISSUE THREAD

**Issue by didd** [microsoft/playwright-test#192]
## Expected Behavior
3 passed

## Current Behavior
  Timeout of 30000ms exceeded

## Steps to Reproduce
I used the example given [here](https://github.com/microsoft/playwright-test/#write-a-test). Then run :
1. npx folio

## Detail
![image](https://user-images.githubusercontent.com/35398733/102255969-dd09b580-3f1b-11eb-82f1-94a1a66c83b3.png)

## Environment

- @playwright/test:  0.162.0
- Operating System: Windows 10
- Node.js version: 12.18.3
- Browser: [Chromium]

**Comment by nrhoffmann** [comment]
The example test is actually broken. If you go to https://playwright.dev/ and inspect the page you will find that there isn't and element with the class `home-navigation`. What is happening here is the `page.innerText(".home-navigation")` actually waits for the element to become visible. So, `innerText` times out after 30 seconds (by default), but by then the test times out too.

**Comment by mxschmitt** [comment]
Good catch @nrhoffmann, created a corresponding patch here which fixes that #192
