### ISSUE TITLE
Run 'pytest-playwright': No module named 'playwright.main'

### ISSUE THREAD

**Issue by ASAS1314** [microsoft/playwright-test#193]
version:
playwright        0.162.2
pytest-playwright 0.0.9
error msg:
Traceback (most recent call last):
  File "D:/workspaces/openspaces/playwright-python/venv/Lib/site-packages/pytest_playwright/pytest_playwright.py", line 23, in <module>
    from playwright.main import SyncPlaywright
ModuleNotFoundError: No module named 'playwright.main'

playwright.main has already rename to _main.

**Comment by mxschmitt** [comment]
Are you using the Playwright Python version from PIP? Seems like on PIP these rename was not yet released, so I can't reproduce it yet. But yes it needs to be fixed as soon as a new Playwright Python version will get released.

**Comment by mxschmitt** [comment]
@ASAS1314 version 0.0.10 of pytest-playwright got released which fixes that issue.
