### ISSUE TITLE
How can I update mock fixture at test runtime?

### ISSUE THREAD

**Issue by haikyuu** [microsoft/playwright-test#198]
My use case is quite simple:
- my app performs a request to the backend -> some state is ON
- expect the UI to display ON
- my app performs a request to the backend -> some state is OFF
- expect UI to display OFF

I used fixtures to mock a couple of routes, and I want to re-mock one route in the middle of my test. I've tried to do that, but it didn't work:
```typescript
// test...
mockedContext.route(...)
// more tests
```

If it's not possible to implement now, is there a workaround that can work for me?

**Comment by haikyuu** [comment]
It turns out I can call `page.route(...)` the same way. It's a good thing to add to the network mocking docs.

**Comment by mxschmitt** [comment]
The new test-runner is quite different, please create a new issue if you still face into that issue.
