### ISSUE TITLE
Allow overriding parameters in my config

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright-test#199]
Right now it looks like all parameters are specified on the command line. This makes me have a long command to run my tests, like `npx folio -p browserName=chromium`. If you let me override the fixtures, you should also let me override the parameters. Or give me a config file like jest that lets me specify all the default parameters. Adding so many command line options is very awkward.

**Comment by JoelEinbinder** [comment]
Right now I am hacking around this by overriding `browserType` in my code:

```js
fixtures.browserType.override(async({}, runTest) => {
  await runTest(chromium);
});
```

But this isn't ideal, because it makes `browserName` dangerous. If anyone touches `browserName`, it will cause my tests to run three times, and the browser name will be wrong if its not chromium.

**Comment by mxschmitt** [comment]
Closing since we have a config file now.
