### ISSUE TITLE
How can I re-use page instance from previous it block?

### ISSUE THREAD

**Issue by mranosa** [microsoft/playwright-test#204]
I would like to reuse the last instance of my page, from a previous it block. How do I do that?

**Comment by mxschmitt** [comment]
Tests in general should be in-depended from each other, so it's not a good practise to share state between them. Each test has its own Playwright browser context to guarantee they can ran in-dependent from each other.

What kind of scenario are you trying to implement?

**Comment by mranosa** [comment]
Gotcha, I wanted to chop a long flow into smaller blocks of tests, and share the state of the last step to the next one.
