### ISSUE TITLE
Run in Debug Mode

### ISSUE THREAD

**Issue by qkdreyer** [microsoft/playwright-test#208]
It looks like `folio` doesn't care about the `PWDEBUG` env variable, as documented [here](https://playwright.dev/docs/debug/#run-in-debug-mode).

Is the command `PWDEBUG=1 npx folio --test-match 'tests/**/?(*.)+(e2e).ts?(x)' --param browserName=chromium` supposed to launch playwright in debug mode or am I missing something ?

**Comment by nrhoffmann** [comment]
Found and fixed this issue. Let's hope it gets merged.

**Comment by mxschmitt** [comment]
Should be fixed with the [new test-runner](https://playwright.dev/docs/test-intro) which got released yesterday.
