### ISSUE TITLE
Error when running “npx folio”: First argument must use the object destructuring pattern: _x

### ISSUE THREAD

**Issue by dav1d992** [microsoft/playwright-test#210]
I have playwright tests and I run the tests with this command: `npx folio`.

But when I run the tests I receive this error message: 

`First argument must use the object destructuring pattern: _x`

I did try to delete the .babelrc file which should work according to this [thread](https://github.com/microsoft/folio/issues/160). But that didn't change anything for me. 

What could be done to address this error?

some-test.spec.ts: 
```
import { it, expect, describe } from "@playwright/test";

describe('test', () => {
  it("is a basic test with the page", async ({ page }) => {
    await page.goto("https://playwright.dev/");
    const name = await page.innerText(".navbar__title");
    expect(name).toBe("Playwright");
  });
}) 
```

**Comment by mxschmitt** [comment]
Hello, could you try it with the latest folio version? `npm install folio@latest`?
