### ISSUE TITLE
Is there a jsdom configuration as in Jest

### ISSUE THREAD

**Issue by DoroNahari** [microsoft/playwright-test#216]
I tried to configure playwright-test in my project and i get "window is not defined"

I think i need the jsdom test env like in jest: https://jestjs.io/docs/en/configuration#testenvironment-string

**Comment by mxschmitt** [comment]
There is no jsdom integration planned. Evaluating JavaScript is only supported via the evaluation methods, e.g. page.evaluate: https://playwright.dev/docs/api/class-page#page-evaluate
