### ISSUE TITLE
Can not set the headful parameter properly

### ISSUE THREAD

**Issue by Kazimirkas** [microsoft/playwright-test#222]
On macOS, node v14.15.1
it works ok only like so
`HEADFUL=true npx folio`

but, if I try
`npx folio --param headful` or `npx folio --p headful` or `npx folio --p headful=true` 
it ignores the parameter and works in headless mode

**Comment by Kazimirkas** [comment]
thanks

**Comment by Kazimirkas** [comment]
@mxschmitt . May I ask about your next release plans?  😃

**Comment by mxschmitt** [comment]
There was a new version released: https://www.npmjs.com/package/@playwright/test

**Comment by Kazimirkas** [comment]
Yes, now it works as expected, thank you!
