### ISSUE TITLE
playwright-1.9.1 --param headful not working

### ISSUE THREAD

**Issue by wongchristopher** [microsoft/playwright-test#226]
Hey I'm using playwright-0.191.0. 

It looks like the --param headful no longer works in this version.   

If I downgrade to 0.180.0 it starts working again.  

Looks like it may have to do with this pull request https://github.com/microsoft/playwright-test/pull/212

**Comment by rainy-me** [comment]
the latest release(0.192.0) fixed this. https://github.com/microsoft/playwright-test/issues/222#issuecomment-796361124
