### ISSUE TITLE
QUESTION : How to pass folio parameters programmatically while using playwright-test?

### ISSUE THREAD

**Issue by fasatrix** [microsoft/playwright-test#228]
is it possible (and if yes how) to pass folio CLI --param programmatically while using playwright-test? I was expecting the following to open chrome headful but it doesn't. I looked at the documentation but doesn't have many examples.

```
import {folio} from '@playwright/test'
import {chromium,LaunchOptions } from 'playwright';

const fixtures  = folio.extend()

fixtures.browserOptions.override(async({browserOptions},runTest) => {
  const modifiedOptions: LaunchOptions = {
    ...browserOptions,
    ...chromium.launch({
      headless: false
    })
  }
  await runTest(modifiedOptions);  
});

const extendedfolio = fixtures.build();
export const it = extendedfolio.it;
export const describe = extendedfolio.describe;
```

**Comment by mxschmitt** [comment]
Closing as part of the triage since the [new test-runner](https://playwright.dev/docs/test-intro) is fundamental different. Please create a new issue if you still face into that error.
