### ISSUE TITLE
Customise snapshot directory

### ISSUE THREAD

**Issue by badsyntax** [microsoft/playwright-test#229]
Hi there. I originally posted this issue in the folio repo, but as there's been no responses I assume it's the wrong repo. The original issue is here: https://github.com/microsoft/folio/issues/187

Simply, I would like to have an option to control the snapshot directory name, to exclude any OS specific names, to allow me to generate golden snapshots on MacOS and to run the tests on Linux.

Thanks!

**Comment by mxschmitt** [comment]
It's not recommended to share such screenshot between operating systems, since it mostly behaves quite differently on Windows, Mac, or Linux. Also in Docker e.g. thats afaik why such a decision was made.

**Comment by badsyntax** [comment]
Thanks for the reply! That actually makes sense. I will generate my golden snapshots within a linux docker container to match my CI environment.
