### ISSUE TITLE
Latest version wasn't released to npm

### ISSUE THREAD

**Issue by haikyuu** [microsoft/playwright-test#230]
This is a follow up of https://github.com/microsoft/playwright/issues/5591#issuecomment-811837895 

Version was bumped but not released to npm

Thanks

**Comment by mxschmitt** [comment]
cc @aslushnikov

**Comment by aslushnikov** [comment]
@haikyuu thank you for the heads up! Fixed.

**Comment by haikyuu** [comment]
most welcome  @aslushnikov
