### ISSUE TITLE
How to use jest-extended?

### ISSUE THREAD

**Issue by srguiwiz** [microsoft/playwright-test#231]
Found https://github.com/jest-community/jest-extended via https://jestjs.io/docs/expect .

Want to use `jest-extended` with playwright-test.  For example for `.toStartWith`.

How can one make this work?  No luck so far.

There is an installation section https://github.com/jest-community/jest-extended#installation easy to follow, and a setup section https://github.com/jest-community/jest-extended#setup .

Did the obligatory
```
npm install jest-extended
```

Added to our `package.json` a `jest` section
``` json
{
  "name": "our-e2e",
  "version": "0.1.0",
  "jest": {
    "setupFilesAfterEnv": [
      "jest-extended"
    ]
  },
  "dependencies": {
    "@playwright/test": "^0.192.0",
    "jest-extended": "^0.11.5"
  }
}
```

When running a test with `toStartWith` instead of `toContain`
``` javascript
expect(page.url()).toStartWith("https://some/thing");
```

am getting **error**

```
TypeError: expect(...).toStartWith is not a function
```

First without, and then created a top level file `global.d.ts` with
``` javascript
import "jest-extended";
```

Same error message in all circumstances.

**Comment by mxschmitt** [comment]
This project is not using Jest. But its using the expect library, so calling something like that should work:

```ts
import jestExtendedMatchers from 'jest-extended/dist/matchers/index.js'

expect.extend(jestExtendedMatchers)
```

but having the typings working is probably kinda hard then. 

Relates: https://github.com/microsoft/folio/issues/185

**Comment by srguiwiz** [comment]
Unfortunately in `node_modules/folio/out/index.d.ts` it says
``` javascript
export { expect } from './expect';
```
which comes from `node_modules/folio/out/expect.d.ts` saying
``` javascript
import type { Expect } from './expectType';
export declare const expect: Expect;
```
which comes from `node_modules/folio/out/expectType.d.ts` saying
``` javascript
export declare type Expect = {
    <T = unknown>(actual: T): Matchers<T>;
    [id: string]: AsymmetricMatcher;
    not: {
        [id: string]: AsymmetricMatcher;
    };
};
```
which in our fixture after
``` javascript
export const folio = builder.build();
export const test = folio.test;
export const expect = folio.expect;
```
makes `expect` to be of `Matchers` type, which doesn't have an `extend` method, so what have failed calling
``` javascript
expect.extend(jestExtendedMatchers)
```

Apparently we'd want an `Expect` object of the type defined in `node_modules/expect/build/types.d.ts` being
``` javascript
export declare type Expect = {
    <T = unknown>(actual: T): Matchers<T>;
    addSnapshotSerializer(arg0: any): void;
    assertions(arg0: number): void;
    extend(arg0: any): void;
…
```

**Comment by mxschmitt** [comment]
Seems related and blocked by that: https://github.com/microsoft/folio/issues/185

Feel free to upvote that.
