### ISSUE TITLE
npx folio --config ... parameter unknown

### ISSUE THREAD

**Issue by juan-morales** [microsoft/playwright-test#236]
`npx folio --config=config.js`

is not working, I gt an error saying that the --config parameter is not known.

Am I doing something wrong here?

**Comment by mxschmitt** [comment]
The version was not released yet. Please refer to the latest release readme:
 https://www.npmjs.com/package/@playwright/test

https://www.npmjs.com/package/folio

**Comment by juan-morales** [comment]
Thanks a lot. Works now
