### ISSUE TITLE
How to run tests longer than timeout 30s / 30000ms

### ISSUE THREAD

**Issue by srguiwiz** [microsoft/playwright-test#238]
`npx folio --help` says
```
--timeout <timeout>      Specify test timeout threshold in milliseconds (default: 10000)
```

which is implemented in folio's `cli.js` as

``` javascript
    if (command.timeout)
        fixtures_1.config.timeout = parseInt(command.timeout, 10);
```

and gets its default from folio's `config.js` as

``` javascript
    timeout: 10000,
```

but then it gets fixed up in playwright's `index.js` as

``` javascript
// Test timeout for e2e tests is 30 seconds.
folio_1.config.timeout = 30000;
```

and command line option `--timeout` hence has **no effect**.

After much investigation we found a **workaround** in fixtures to do this:

``` javascript
import { config } from "@playwright/test";
config.timeout = 60000;
```

This must be at top level in the fixture.  If invoked inside an `override` or `init` method, then it has no effect, being too late.

We have to test filling out a really long form in one sitting on a single page, as a main use case, and 30 seconds was barely not enough.

Notably tests failed often without giving an exact cause, but along the line of `Protocol error (Input.dispatchKeyEvent): Page closed` and `Protocol error (Page.dispatchMouseEvent): Target closed.undefined` etc...  Only sometimes it would explicitly say `Timeout of 30000ms exceeded.`

**Update**:  To run successfully by allowing 60 seconds, we have to both use `--timeout=60000` on the command line **and** in a fixture have
``` javascript
import { config } from "@playwright/test";
config.timeout = 60000;
```

**Comment by mxschmitt** [comment]
When using the new `npm install -D @playwright/test@next`, then you can do something like that:

```js
setConfig({
  timeout: 60 * 1000,
})
```
See [here](https://github.com/mxschmitt/try-playwright/blob/b7ae1bd92354e2732149f7d05157bafc1dcbad67/e2e/config.ts#L6-L9) for a full example:

**Comment by srguiwiz** [comment]
Yes, a `setConfig` in a `config.ts` did work for us now to set the `timeout` in the new playwright-test.  Thank you.
