### ISSUE TITLE
Documentation: Custom Fixtures to Support POMs

### ISSUE THREAD

**Issue by BillyBolton** [microsoft/playwright-test#242]
It seems that fixtures are no longer supported or have changed with v0.1101.0.  Can there be documentation on what these changes are and/or how to extend built-in fixtures? (I'm wondering if the documented config.ts folio example is suppose to replace this, but it doesn't show how to extend a built-in fixture.)

This was my fixture before as per the documentation, but no longer works due to changes in modules, (ie. folio no longer included in @playwright/test):

```// In tests/fixtures.ts
import { folio as baseFolio } from '@playwright/test'; //this is no longer available
import { IndexPage } from "../PO/IndexPage";

require('dotenv').config();
const baseURL = process.env.BASE_URL;

// Extend built-in fixtures and declare types for new fixtures
const builder = baseFolio.extend<{ indexPage: IndexPage }>();

// In fixtures.ts
builder.indexPage.init(async ({ page }, runTest) => {
    // get built-in page and wrap with POM
    const indexPage = new IndexPage(page, baseURL);

    // pass this to your test
    runTest(indexPage);
});

// Build and export the modified fixtures
const folio = builder.build();
export const it = folio.it;
export const expect = folio.expect;
export const describe = folio.describe; ```

**Comment by dgozman** [comment]
We have changed the underlying Folio from fixtures to environments. Sorry for the temporary hiatus - we'll become stable with v1.0 release. Let me write a snippet for you for now, and we'll update documentation soon. Following the [write a configuration file](https://github.com/microsoft/playwright-test#write-a-configuration-file) section, here is an example config that gives you POM:

```ts
// config.ts

import { PlaywrightEnv, newTestType, setConfig, TestInfo } from "@playwright/test";

setConfig({
  testDir: __dirname,  // Search for tests in this directory.
  timeout: 30000,  // Each test is given 30 seconds.
});

// Extend the default environment to add any test arguments, for example POMs.
class MyEnv extends PlaywrightEnv {
  async beforeEach(testInfo: TestInfo) {
    // Get all default arguments, including Page.
    const result = await super.beforeEach(testInfo);
    // Create your POM.
    const indexPage = new IndexPage(result.page, baseURL);
    // Return default arguments and new POM.
    return { ...result, indexPage };
  }
}

// Declare "indexPage" test argument for types in IDE.
export const test = newTestType<{ indexPage: IndexPage }>();
export { expect } from "@playwright/test";

// Run tests in three browsers.
const options = {
  headless: true,  // Run tests in headless browsers.
  viewport: { width: 1280, height: 720 },
};
test.runWith(new MyEnv('chromium', options), { tag: 'chromium' });
test.runWith(new MyEnv('firefox', options), { tag: 'firefox' });
test.runWith(new MyEnv('webkit', options), { tag: 'webkit' });
```

Now you can use the `test` from the configuration file:
```ts
// foo.spec.ts

import { test, expect } from './config';

test('my test', async ({ indexPage }) => {
});
```

Let me know whether this works for you. Note that we are open for suggestions and work on improving test ergonomics.

**Comment by BillyBolton** [comment]
@dgozman Thank you for sending that over. Took a while to figure out fixtures properly so I was a bit worried that work was for naught.

The new config process looks promising. I wasn't clear what the TestInfo was but your comments make it more clear. I'm looking forward to the refreshed documentation down the road!

Thanks again. I'm working a lot with Playwright so I'll send some more info down the road as they come. Great stuff so far.

**Comment by srguiwiz** [comment]
@dgozman  Do I understand correctly if one wants to use one's own `class MyEnv extends PlaywrightEnv` then one must not use `ChromiumEnv`, `FirefoxEnv`, and `WebKitEnv` currently mentioned in the `README.md`.  Maybe those three browser-named `Env` as they exist today effectively are class hierarchy cul-de-sacs that shouldn't exists because it will be a perplexing situation for anyone who tries figuring how to build on top of them?

**Comment by dgozman** [comment]
@srguiwiz Thank you for the feedback, we'll look into it.

**Comment by srguiwiz** [comment]
@dgozman Can you please update your code example for playwright/test 0.1102.0 ?

At
``` typescript
import { PlaywrightEnv, newTestType, setConfig, TestInfo } from "@playwright/test";
```
the three imports `PlaywrightEnv`, `newTestType`, `setConfig` no longer exist.

Would like to follow you on the way to 1.0 by adjusting what we already have.

**Comment by BillyBolton** [comment]
I'm working on a project to use playwright-test in a larger organization. Is there a roadmap I can follow / estimated time frame that the stable 1.0v might be available? This timeline affects the stakeholders of my project so any info would be appreciated, (instead of refactoring during this time).

**Comment by srguiwiz** [comment]
@BillyBolton As original reporter of this issue you can reopen it.

**Comment by BillyBolton** [comment]
Reopening due to popular demand 😉 

(*With hesitation* I understand we're still in unstable versions.)

**Comment by mxschmitt** [comment]
We now have an official example for using the POM pattern with the [new test-runner](https://playwright.dev/docs/test-intro) which got released yesterday. See [here](https://playwright.dev/docs/test-pom) for the example.
