### ISSUE TITLE
PlaywrightEnv subclasses

### ISSUE THREAD

**Issue by dannycoates** [microsoft/playwright-test#248]
When extending `PlaywrightEnv` I'd like to be able to access `_browser` (and maybe others) from my own `beforeAll` and `afterAll` methods. It'd be nice if it was `protected` or had a getter I could access.

**Comment by mxschmitt** [comment]
Closing as part of the triage since the [new test-runner](https://playwright.dev/docs/test-intro) is quite different. Please create a new issue if its still persistent for you with the new fixture infra.
