### ISSUE TITLE
Add option to set devtools flag to true

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright-test#255]
to debug my tests I add the following snippet:

```ts
import { folio as baseFolio } from '@playwright/test';
type TestFixtures = {};
const builder = baseFolio.extend<TestFixtures>();

if (process.env.DEBUG?.includes('pw:api')) {
    builder.browserOptions.override(async ({ }, runTest) => await runTest({ headless: false, devtools: true }));
}

export const folio = builder.build();
```

it would be nice to be able to trigger something like this using only command line args

**Comment by mxschmitt** [comment]
With the new test-runner, you can now add such custom logic to the setup file: https://playwright.dev/docs/test-configuration#different-options-for-each-browser
