### ISSUE TITLE
npx folio --help first reads files

### ISSUE THREAD

**Issue by srguiwiz** [microsoft/playwright-test#258]
Per README file
```
# See all options
npx folio --help
```
apparently first looks at the directory instead of just listing help.

How to find out:  Have test files it can't handle.

Expected behavior:  `npx folio --help` shows help under all circumstances.

**Comment by srguiwiz** [comment]
Apparently already reported at https://github.com/microsoft/folio/issues/227 .

**Comment by mxschmitt** [comment]
This should be fixed in the latest version. Please refer to the new test-runner here: https://playwright.dev/docs/test-intro
