### ISSUE TITLE
Target Closed

### ISSUE THREAD

**Issue by burritoIand** [microsoft/playwright-test#263]
I've made an attempt to migrate my working mocha test suite to use the playwright test runner today and am getting the same failure on multiple tests.

![image](https://user-images.githubusercontent.com/230757/118897941-3eb1bf80-b8c0-11eb-963a-ede4ee2139cc.png)

Any idea what could cause this?

**Comment by mxschmitt** [comment]
The new test-runner which got released yesterday is quite different. So please test if its still reproducible there and open a new issue if its still persistent: https://playwright.dev/docs/test-intro
