### ISSUE TITLE
QUESTION: Is there any roadmap for 1.0 playwright-test release?

### ISSUE THREAD

**Issue by radekBednarik** [microsoft/playwright-test#267]
Hello,
I would like to ask, if there is any public roadmap or date, when it is planned to release playwright-test as production ready (1.0).
I am currently evaluating what would be the best test runner with playwright for a really long-term project of e2e web app testing and I would be nice to know, how much far in the future the release is.
Thank you very much

RB

**Comment by mxschmitt** [comment]
Hi, there is no official eta yet but I personally would say that it should be ready in the next few weeks or at least usable which does not result in breaking changes anymore. So stay tuned!

**Comment by radekBednarik** [comment]
@mxschmitt hello, thanx for the answer, I am definitely tuned 👍
