### ISSUE TITLE
each keyword for data-driven test

### ISSUE THREAD

**Issue by roughsoft** [microsoft/playwright-test#94]
for data-driven test ,the table parameters is great feature ,so if you can support each keyword ,it will be awesome

**Comment by arjun27** [comment]
Hi @roughsoft, we've updated the docs for parameters: https://github.com/microsoft/playwright-test#parameterize-your-tests

Take a look and tell us what you think?

**Comment by roughsoft** [comment]
thank you！

**Comment by roughsoft** [comment]
if we can provide some data-driven test sample code in sample dir，it would be great

**Comment by roughsoft** [comment]
@arjun27
